name: Build

on:
  # Build all PRs
  pull_request: {}
  push:
    branches:
      - main

# Help Dependabot checks run
permissions:
  checks: write
  contents: read
  packages: write
  # Eventually support deployment tracking.
  deployments: write

jobs:
  vite:
    name: Vite/TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  docker:
    name: Docker
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.server-tag }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        id: build
        uses: firehed/multistage-docker-build-action@v1.7
        with:
          repository: ghcr.io/snapauthapp/demo-web
          stages: node-dependencies
          server-stage: server
          parallel: true
